[tool.poetry]
name = "admixslug"
version = "0.0.0"
description = "A genotype-likelihood method for contaminated low-coverage archaic human genetic data"
authors = ["benjamin_peter <benjamin_peter@eva.mpg.de>", "arev_suemer@eva.mpg.de"]
license = "BSD"
readme = "README.md"
packages = [
    { include = "admixslug" },
]

[build-system]
requires = ["poetry-core>=1.2.0", 
    "poetry-dynamic-versioning", 
    "setuptools", 
    "scipy>=1.1"]
#build-backend = "poetry.core.masonry.api"
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry.build]
generate-setup-file = true
script = 'build.py'

[tool.poetry.dependencies]
python = ">=3.10"
pandas = ">=2.2"
numba = ">=0.53"
numpy = ">=1.23"
scipy = ">=1.1"
pybedtools = ">=0.10"
pysam = ">=0.15.0"
pyyaml = ">=5.0"
setuptools = ">=75"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.2.0"
pytest-console-scripts = ">= 1.4.1"
pytest-coverage = "^0.0"


[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
bump = false
pattern  = "^(?P<base>\\d+\\.\\d+\\.\\d+)(-?((?P<stage>[a-zA-Z]+)\\.?(?P<revision>\\d+)?))?"


[tool.poetry.scripts]
admixslug-bam = 'admixslug:bam2'
admixslug-profile = 'admixslug:profile_slug'
admixslug-ref = 'admixslug:do_ref'
admixslug = 'admixslug:run_sfs'

